// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/request/article.proto

package request // import "JupiterBlog/micro/protobuf/request"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ArticleInfo struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleInfo) Reset()         { *m = ArticleInfo{} }
func (m *ArticleInfo) String() string { return proto.CompactTextString(m) }
func (*ArticleInfo) ProtoMessage()    {}
func (*ArticleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_article_336f8d19102638d4, []int{0}
}
func (m *ArticleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleInfo.Unmarshal(m, b)
}
func (m *ArticleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleInfo.Marshal(b, m, deterministic)
}
func (dst *ArticleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleInfo.Merge(dst, src)
}
func (m *ArticleInfo) XXX_Size() int {
	return xxx_messageInfo_ArticleInfo.Size(m)
}
func (m *ArticleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleInfo proto.InternalMessageInfo

func (m *ArticleInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*ArticleInfo)(nil), "request.ArticleInfo")
}

func init() {
	proto.RegisterFile("protobuf/request/article.proto", fileDescriptor_article_336f8d19102638d4)
}

var fileDescriptor_article_336f8d19102638d4 = []byte{
	// 113 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x2f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0xd1, 0x4f, 0x2c, 0x2a,
	0xc9, 0x4c, 0xce, 0x49, 0xd5, 0x03, 0x4b, 0x08, 0xb1, 0x43, 0x85, 0x95, 0x64, 0xb9, 0xb8, 0x1d,
	0x21, 0x32, 0x9e, 0x79, 0x69, 0xf9, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0x2c, 0x41, 0x4c, 0x99, 0x29, 0x4e, 0x2a, 0x51, 0x4a, 0x5e, 0xa5, 0x05, 0x99, 0x25, 0xa9,
	0x45, 0x4e, 0x39, 0xf9, 0xe9, 0xfa, 0xb9, 0x99, 0xc9, 0x45, 0xf9, 0xfa, 0xe8, 0x66, 0x27, 0xb1,
	0x81, 0x45, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x02, 0x2b, 0x47, 0xa9, 0x76, 0x00, 0x00,
	0x00,
}
