[jupiter.server.http]
    host = "127.0.0.1"
    port = 9099
[jupiter.etcdv3.default]
    endpoints=["127.0.0.1:2379"]
    secure = false
[jupiter.registry.wh]
    configKey="jupiter.etcdv3.default"
    timeout = "1s"
[jupiter.mysql.default]
   connMaxLifetime = "300s"
   debug = true
   dsn = "root:123456@tcp(127.0.0.1:3306)/test?charset=utf8&parseTime=True&loc=Local&readTimeout=1s&timeout=1s&writeTimeout=3s"
   level = "panic"
   maxIdleConns = 50
   maxOpenConns = 100
[jupiter.client.article]
    address = "etcd:///article"
    balancerName = "round_robin" # 默认值
    block =  false # 默认值
    dialTimeout = "0s" # 默认值